# Generated by Django 5.1.5 on 2025-10-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
