# Generated by Django 5.1.5 on 2025-10-21 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_leitor_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='livro',
            name='copias_disponiveis',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cópias Disponíveis'),
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='livro',
            name='numero_copias',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Cópias Totais'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(help_text='13 Caracteres ISBN', max_length=13, unique=True),
        ),
    ]
